services:
  postgres:
    image: postgres:15-alpine
    container_name: chernika_postgres_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chernika_network_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chernika_backend_dev
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_BASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
      
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      GIN_MODE: ${GIN_MODE}
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/tmp
      - /app/api/docs
    networks:
      - chernika_network_dev
    restart: unless-stopped

volumes:
  postgres_data_dev:
    driver: local

networks:
  chernika_network_dev:
    driver: bridge