scalar Time

# -----------------------APP MODELS----------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------
type Category {
  id: ID!
  name: String!
  description: String
}

type Product {
  # Identifications
  id: ID!
  slug: String!
  article: String!

  # info
  name: String!
  description: String
  price: Float!
  isOutOfStock: Boolean!
  category: Category
  imagesUrls: [String!]!

  # time/date
  releasedAt: Time!
}
# -------------------------------------------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------


# ---------------------UTILITY MODELS--------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------
enum SortDirection {
  ASC
  DESC
}
# -------------------------------------------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------


# ---------------------REQUESTS--------------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------
enum ProductsSortField {
  PRICE
}

input ProductSort {
  direction: SortDirection!
  field: ProductsSortField!
}

type Query {  
  products(
    sort: ProductSort!
  ): [Product!]!
}

# type Mutation {
  
# }
# -------------------------------------------------------------
# -------------------------------------------------------------
# -------------------------------------------------------------
